---
title: FirstRate Carpentry
author: Ben Pettinger
email: ben@firstratecarpentry.com
description: THIS IS THE SITE DESCRIPTION - WHERE DOES IT SHOW UP?
baseurl: "/ubuild-jekyll"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
